[project]
name = "drips-complex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "giotto-ph>=0.2.4",
    "numpy>=2.2.2",
    "plotly>=6.0.0",
    "scikit-learn>=1.6.1",
    "typing-extensions>=4.12.2",
]
